version: '2.3'

services:
  # ############################
  # EXTERNAL SERVICES
  # ############################
  mongo:
    container_name: mongo
    image: mongo:4.4.13-focal
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    entrypoint: ['/usr/bin/mongod', '--bind_ip_all', '--replSet', 'rs0']
    volumes:
      - mongo:/data/db
    networks:
      - insightful
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 127.0.0.1:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 40s
    extra_hosts:
      - host.docker.internal:host-gateway

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.16.3
    restart: always
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - insightful
    extra_hosts:
      - host.docker.internal:host-gateway

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.5
    hostname: zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - '2181:2181'
    networks:
      - search-engine
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-logs:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: zookeeper
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=9101
    extra_hosts:
      - host.docker.internal:host-gateway

  kafka:
    image: confluentinc/cp-kafka:5.5.5
    hostname: kafka
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    networks:
      - search-engine
    volumes:
      - kafka:/kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_LOG_FLUSH_INTERVAL_MS: 60000
      KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 1000
      KAFKA_LOG_RETENTION_HOURS: 240
      KAFKA_LOG_RETENTION_BYTES: 536870912000
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: kafka
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=9101
    extra_hosts:
      - host.docker.internal:host-gateway

  kafka_ui:
    image: provectuslabs/kafka-ui:0.3.1
    hostname: kafka_ui
    container_name: kafka_ui
    restart: always
    ports:
      - '7036:8080'
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_BROKERCONNECT: kafka:29092
    depends_on:
      - kafka
      - zookeeper
    networks:
      - search-engine

volumes:
  redis:
    driver: local
  zookeeper-data:
    driver: local
  zookeeper-logs:
    driver: local
  kafka:
    driver: local
  elasticsearch:
    driver: local
  mongo:
    driver: local
  minio:
    driver: local

networks:
  search-engine:
