import Head from 'next/head';
import { useForm } from '@mantine/form';
import { TextInput, Button } from '@mantine/core';
import { useRouter } from 'next/router';

export default function Home() {
    const router = useRouter();
    const form = useForm({
        initialValues: { search: router?.query?.search?.toString() ?? '' },
        validate: {
            search: (value) => (!value ? 'Please enter a search term' : null),
        },
    });

    const onSubmit = (values: { search: string }) => {
        console.log('here');
        const search = values.search;
        router.replace({
            pathname: '/',
            query: { search },
        });
        router.push({
            pathname: '/results',
            query: { search },
        });
    };

    return (
        <>
            <Head>
                <title>Search Engine</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div
                style={{
                    width: '100vw',
                    marginTop: 300,
                    display: 'flex',
                    flexDirection: 'column',
                    justifyContent: 'center',
                    alignItems: 'center',
                }}
            >
                <h1>Gogol</h1>
                <form
                    onSubmit={form.onSubmit((values) => onSubmit(values))}
                    style={{ display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center' }}
                >
                    <TextInput style={{ width: 350 }} placeholder="Enter your keyword" {...form.getInputProps('search')} />
                    <Button type="submit" mt="sm">
                        Gogol search
                    </Button>
                </form>
            </div>
        </>
    );
}
