import Head from 'next/head';
import { Inter } from '@next/font/google';
import { useForm } from '@mantine/form';
import { TextInput, Button } from '@mantine/core';
import { useRouter } from 'next/router';
const inter = Inter({ subsets: ['latin'] });

export default function Home() {
    const router = useRouter();
    const form = useForm({
        initialValues: { search: '' },

        // functions will be used to validate values at corresponding key
        validate: {
            search: (value) => (!value ? 'Please enter a search term' : null),
        },
    });

    const onSubmit = (values: { search: string }) => {
        const search = values.search;
        router.push({
            pathname: '/results',
            query: { search },
        });
    };

    return (
        <>
            <Head>
                <title>Search Engine</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div style={{ width: '100vw', height: '100vh', display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
                <form onSubmit={form.onSubmit(onSubmit)}>
                    <TextInput label="Name" placeholder="Name" {...form.getInputProps('search')} />
                    <Button type="submit" mt="sm">
                        Submit
                    </Button>
                </form>
            </div>
        </>
    );
}
